---
# This file is managed by the stacks toolchain. It may be overwritten by
# updates to the template. Your customizations should be placed inside the
# .kitchen.local.yml, which will not be overwritten by newer templates.
# If you need to override the driver, do it in ~/.kitchen/config.yml or using
# environment variables like VAGRANT_DEFAULT_PROVIDER.

driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 9200, host: 9200, auto_correct: true}]  # elastic
  - ["forwarded_port", {guest: 80,   host: 8080, auto_correct: true}]  # kibana
  - ["forwarded_port", {guest: 443,   host: 8443, auto_correct: true}] # ssl

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      iptables:
        allow_ssh_from_world: true
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
      omnibus_updater:
        enabled: false
    elasticsearch:
      allocated_memory: '512m'
      network:
        host: '127.0.0.1'
      index:
        number_of_replicas: 0
        # so the kitchen node doesn't have unallocated replica shards
        # and comes up green (healthy) instead of yellow

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default # server
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[elkstack::java]
      - recipe[elkstack::cluster] # not testing single, it's practically the same
    attributes:
      elasticsearch:
        discovery:
          zen:
            minimum_master_nodes: 1 # since search returns more than one, but they are fake

  - name: default-nokeypair # server
    run_list:
      - recipe[elkstack::java]
      - recipe[elkstack::cluster] # not testing single, it's practically the same
    attributes:
      elasticsearch:
        discovery:
          zen:
            minimum_master_nodes: 1 # since search returns more than one, but they are fake

  - name: agent
    data_bags_path: "test/integration/agent/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/agent/encrypted_data_bag_secret"
    run_list:
      - recipe[wrapper::logstash_override]
      - recipe[elkstack::java]
      - recipe[elkstack::agent]

  # no tests needed for this; just needed it to converge
  - name: agent-autokeypair
    data_bags_path: "test/integration/agent/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/agent/encrypted_data_bag_secret"
    attributes:
      elkstack:
        config:
          lumberjack_data_bag: "lumberjack-auto"
    run_list:
      - recipe[wrapper::logstash_override]
      - recipe[elkstack::java]
      - recipe[elkstack::agent]

  - name: forwarder
    data_bags_path: "test/integration/agent/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/agent/encrypted_data_bag_secret"
    run_list:
      - recipe[elkstack::forwarder]
